In [ ]:
# Numpy

import numpy as np

# creation of array
arr=np.array([1,2,3,4])

In [ ]:
#printing of array
arr

array([1, 2, 3, 4])

In [ ]:
#type of array
print(type(arr))

# Use a tuple to create a NumPy array:
arr1=np.array((1,2,3,4))
print(arr1)

<class 'numpy.ndarray'>
[1 2 3 4]


In [ ]:
# Dimensions in Arrays

# Create a 0-D array with value 42
arr=np.array(42)
print(arr)

# Create a 1-D array containing the values 1,2,3,4,5:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# Check how many dimensions the arrays have:

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr.size

12

In [ ]:

arr.dtype

dtype('int64')

In [ ]:
# vectorization

arr = np.array([1,2,3,4])
arr=arr + 10
print(arr)

[11 12 13 14]


In [ ]:
arr = np.array([1,2,3,4])
arr * 2

array([2, 4, 6, 8])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a+b

array([5, 7, 9])

In [ ]:
arr=np.array([1,2,3],dtype=np.int8)

In [ ]:
arr

array([1, 2, 3], dtype=int8)

In [ ]:
# data type conversion
arr = np.array(
    [1,2,3],
    dtype=np.float32
)


In [ ]:

arr = np.array([1,2,3])
#explict data conversion
arr.astype(float)

array([1., 2., 3.])

In [ ]:
arr = np.array([1,2,3])
# size of an element (int8,float32)
arr.itemsize

8

In [ ]:
# total number of bytes used
arr.nbytes

24

In [ ]:
# Python and NumPy support negative indexes.
arr[-1]

np.int64(3)

In [ ]:
# Slicing
# arr[start:end] (Start included, End excluded)
arr[1:4]


array([2, 3])

In [ ]:
#  Step Size (arr[start:end:step])
arr = np.array([10,20,30,40,50,60,70])
arr[0:7:2]

array([10, 30, 50, 70])

In [ ]:
# Step Size
arr[::-1]

array([70, 60, 50, 40, 30, 20, 10])

In [ ]:
# 2D array

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# singlw element
arr[0,0]

# entire row
arr[0]

array([1, 2, 3])

In [ ]:
# entire column
arr[:,2]

array([3, 6, 9])

In [ ]:
# boolean indexing
arr = np.array([10,20,30,40,50])

arr>25


array([False, False,  True,  True,  True])

In [ ]:
# condition
arr[arr>25]

array([30, 40, 50])

In [ ]:
# multiple condition
arr[(arr > 20) & (arr < 50)]

array([30, 40])

In [ ]:
# Important NumPy Behavior: Views
arr = np.array([1,2,3,4])

slice_arr = arr[1:3]

In [ ]:
slice_arr[0] = 100

In [ ]:
arr

array([  1, 100,   3,   4])

In [ ]:
#  Copy When Needed

copy_arr = arr.copy()