In [1]:
# Numpy

import numpy as np

# creation of array
arr=np.array([1,2,3,4])

In [2]:
#printing of array
arr

array([1, 2, 3, 4])

In [5]:
#type of array
print(type(arr))

# Use a tuple to create a NumPy array:
arr1=np.array((1,2,3,4))
print(arr1)

<class 'numpy.ndarray'>
[1 2 3 4]


In [7]:
# Dimensions in Arrays

# Create a 0-D array with value 42
arr=np.array(42)
print(arr)

# Create a 1-D array containing the values 1,2,3,4,5:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
# Check how many dimensions the arrays have:

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [10]:
arr.size

12

In [11]:

arr.dtype

dtype('int64')

In [13]:
# vectorization

arr = np.array([1,2,3,4])
arr=arr + 10
print(arr)

[11 12 13 14]


In [14]:
arr = np.array([1,2,3,4])
arr * 2

array([2, 4, 6, 8])

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a+b

array([5, 7, 9])